### ISSUE TITLE
Project Name?

### ISSUE THREAD

**Issue by abhibeckert** [alcohol/iso3166#62]
Is there a reason this project is named `iso3166`?

Surely `CountryCodes` (or something more inventive) would make this a lot more usable. I personally rename it in all my `use` statements, but I'd rather not do that.

**Comment by hashimaziz1** [comment]
The current name seems the most logical to me. "Country codes" is much broader and includes *at least* 2 other standards, ISO 3166-1 is a common enough standard that it is commonly searched for by developers who need to implement it (this is also how I found it, and probably wouldn't have found it otherwise). If a developer has a personal issue with typing those few letters and numbers, I don't see any disadvantage to the solution of using a `use` statement that you outlined.
