### ISSUE TITLE
Canary Islands is not present in the library

### ISSUE THREAD

**Issue by alexandrmazur96** [alcohol/iso3166#82]
Some users come to us from the Canary Islands, but we can't validate them because this library does not have Canary Islands ISo code representation (`IC`).

It would be good to add it.

**Comment by alcohol** [comment]
It is missing because it is a 3166-2 subdivision code and this library only offers 3166-1 codes. I have no intention of supporting 3166-2 subdivision codes at the moment because then they should all be implemented/represented, and that is a lot of work. Perhaps if it could be automated by parsing official data sources. But that is not the case right now.
